name: tremp_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.12.4
  google_fonts: ^8.1.0
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  geolocator: ^13.0.2
  app_links: ^7.0.0
  share_plus: ^13.1.0
  get_it: ^9.2.1
  flutter_dotenv: ^6.0.1
  flutter_riverpod: ^3.3.1
  maplibre_gl: ^0.26.1
  http: ^1.6.0
  sentry_flutter: ^8.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env

